### PR TITLE
80  security drupal core sa core 2019 006

### PR DESCRIPTION
**Pull request by kpolymorphic**

### CODE REVIEW

**Comment by kpolymorphic** [comment]
@CaroRob - I know you have been dealing with the crazy problems as of late. Just want to remind you about approving this security PR when you get time.

**Comment by purplesky2016** [comment]
We did all the steps, but at one of them, we saw a ":" at the end, and
didn't know how to get out, I accidentally did ctr+z, which generated a
word "stop". After that, we couldn't apply stash, the text says there is
nothing to save. I saved the session and highlighted those key steps below.

*(This is done on dev only, not on prod)*

lError writing session log (raw mode) to file:
putty-log\vps38926.inmotionhosting.com-20190429-105840.log

ogin as: massle6

massle6@vps38926.inmotionhosting.com's password:

Last login: Wed Apr 24 15:08:02 2019 from 50.239.186.130

massle6@masslegalhelp.org [~]# cd /home/massle6/mlhdev/

massle6@masslegalhelp.org [~/mlhdev]# *git diff*

diff --git a/.htaccess b/.htaccess

index 0af48522..9dac8a16 100644

--- a/.htaccess

+++ b/.htaccess

@@ -184,7 +184,8 @@ RewriteCond %{REQUEST_URI}
!^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\

 </IfModule>



 # php -- BEGIN cPanel-generated handler, do not edit

-# NOTE this account's php is controlled via FPM and the vhost, this is a
place holder.

-# Do not edit. This next line is to support the cPanel php wrapper
(php_cli).

-# AddType application/x-httpd-ea-php56 .php .phtml

+# Set the “ea-php70” package as the default “PHP” programming language.

+<IfModule mime_module>

+  AddHandler application/x-httpd-ea-php70 .php .php7 .phtml

+</IfModule>

 # php -- END cPanel-generated handler, do not edit

massle6@masslegalhelp.org [~/mlhdev]# *git fetch origin*

remote: Enumerating objects: 206, done.

remote: Counting objects: 100% (206/206), done.

remote: Total 242 (delta 205), reused 205 (delta 205), pack-reused 36

Receiving objects: 100% (242/242), 23.06 KiB | 11.53 MiB/s, done.

Resolving deltas: 100% (206/206), completed with 183 local objects.

From github.com:MassLegalHelp/MassLegalHelp

 * [new branch]        80--Security-Drupal-core-SA-CORE-2019-006 ->
origin/80--Security-Drupal-core-SA-CORE-2019-006

 * [new branch]        lily-local -> origin/lily-local

   8c71f47a..7112ec57  master     -> origin/master

 * [new tag]           1.4.13     -> 1.4.13

massle6@masslegalhelp.org [~/mlhdev]# *git diff 1.4.13 (we forgot to copy
---name-only at the end)*

diff --git a/.htaccess b/.htaccess

index 0af48522..9dac8a16 100644

--- a/.htaccess

+++ b/.htaccess

@@ -184,7 +184,8 @@ RewriteCond %{REQUEST_URI}
!^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\

 </IfModule>



 # php -- BEGIN cPanel-generated handler, do not edit

-# NOTE this account's php is controlled via FPM and the vhost, this is a
place holder.

-# Do not edit. This next line is to support the cPanel php wrapper
(php_cli).

-# AddType application/x-httpd-ea-php56 .php .phtml

+# Set the “ea-php70” package as the default “PHP” programming language.

+<IfModule mime_module>

+  AddHandler application/x-httpd-ea-php70 .php .php7 .phtml

+</IfModule>

 # php -- END cPanel-generated handler, do not edit

diff --git a/sites/all/modules/custom/mlh_base/mlh_base.module
b/sites/all/modules/custom/mlh_base/mlh_base.module

index e6608db7..d5862d33 100644

--- a/sites/all/modules/custom/mlh_base/mlh_base.module

+++ b/sites/all/modules/custom/mlh_base/mlh_base.module



[1]+  Stopped       (this is where things got messed up)          git diff
1.4.13

massle6@masslegalhelp.org [~/mlhdev]# git stash

Saved working directory and index state WIP on master: 8c71f47a Merge pull
request #31 from
MassLegalHelp/75-78--security-multiple-SA-CORE-2019-004-SA-CONTRIB-2019-042

massle6@masslegalhelp.org [~/mlhdev]# git checkout 1.4.13

Note: checking out '1.4.13'.



You are in 'detached HEAD' state. You can look around, make experimental

changes and commit them, and you can discard any commits you make in this

state without impacting any branches by performing another checkout.



If you want to create a new branch to retain commits you create, you may

do so (now or later) by using -b with the checkout command again. Example:



  git checkout -b <new-branch-name>



HEAD is now at 7112ec57 Merge pull request #33 from MassLegalHelp/lily-local

massle6@masslegalhelp.org [~/mlhdev]# git diff 1.4.13

massle6@masslegalhelp.org [~/mlhdev]# git reset --hard HEAD

HEAD is now at 7112ec57 Merge pull request #33 from MassLegalHelp/lily-local

massle6@masslegalhelp.org [~/mlhdev]# git diff 1.4.13

massle6@masslegalhelp.org [~/mlhdev]# git stash

No local changes to save

massle6@masslegalhelp.org [~/mlhdev]# git stash apply

HEAD detached at 1.4.13

Changes not staged for commit:

  (use "git add <file>..." to update what will be committed)

  (use "git checkout -- <file>..." to discard changes in working directory)



        modified:   .htaccess



Untracked files:

  (use "git add <file>..." to include in what will be committed)



        google0bdb60dd10cce857.html

        sites/all/libraries/youtube-google-analytics/



no changes added to commit (use "git add" and/or "git commit -a")

massle6@masslegalhelp.org [~/mlhdev]# git reset --hard 1.4.12

HEAD is now at 8c71f47a Merge pull request #31 from
MassLegalHelp/75-78--security-multiple-SA-CORE-2019-004-SA-CONTRIB-2019-042

massle6@masslegalhelp.org [~/mlhdev]# git fetch origin

massle6@masslegalhelp.org [~/mlhdev]# git diff 1.4.13 --name-only

sites/all/modules/custom/mlh_base/mlh_base.module

massle6@masslegalhelp.org [~/mlhdev]# git checkout 1.4.13

Previous HEAD position was 8c71f47a Merge pull request #31 from
MassLegalHelp/75-78--security-multiple-SA-CORE-2019-004-SA-CONTRIB-2019-042

HEAD is now at 7112ec57 Merge pull request #33 from MassLegalHelp/lily-local

massle6@masslegalhelp.org [~/mlhdev]# drush -l mlhdev.org updb -y

The following module is missing from the file system: <em
[warning]

class="placeholder">wysiwyg</em>. For information about how to fix

this, see <a href="https://www.drupal.org/node/2487215">the

documentation page</a>. bootstrap.inc:1156

No database updates required
 [success]

massle6@masslegalhelp.org [~/mlhdev]# drush -l mlhdev.org cc all

'all' cache was cleared.
 [success]

**Comment by kpolymorphic** [comment]
@CaroRob and @purplesky2016 - I am guessing based on your description that you may have missed a quote mark somewhere in one of your commands during a copy/paste. What you describe sounds like how the terminal will behave when it is expecting multi-line input.

**Comment by CaroRob** [comment]
I was just concerned that somehow we lost the code spanel created after the last commit ...and that you should know we didn't deploy the change as cleanly as we would have liked. @purplesky2016's commit went to development but not to Master - she worked on it yesterday though and I think she got it working. It's ok to deploy her commit to production now when you do your security patch.

**Pull request merged**
