### PR TITLE
Security  drupal core sa core 2020 007

### PR DESCRIPTION
**Pull request by kpolymorphic**

### CODE REVIEW

**Comment by CaroRob** [comment]
Sorry - getting rusty - am I supposed to test/look at on our dev site, then ok, or....?

**Review by CaroRob — APPROVED** [review]
Let's  just go for it please. and thank you.

**Comment by kpolymorphic** [comment]
For the sake of standard operating procedures you would normally ask for deployments to be on the Dev server for your review. In this case, it is very low risk Drupal Core update.

**Comment by CaroRob** [comment]
Cool - thanks.

**Pull request merged**
